# GERDSEN AI
# Full Stack AI Solutions - From Concept to Production

title: GERDSEN AI - Full Stack AI Solutions
email: garrett@gerdsen.ai
description: >- 
  GERDSEN AI delivers Full Stack AI solutions: from local deployments to cloud workflows, 
  model training to production systems. We handle every layer of your AI infrastructure 
  with expertise in LLMs, vector databases, MLOps, and custom AI development.
baseurl: "/gerdsen-ai" 
url: "https://gerdsenai-admin.github.io"
twitter_username: 
github_username: GerdsenAI-Admin

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from build
exclude:
  - README.md
  - DEPLOYMENT_GUIDE.md
  - deploy.sh
  - JEKYLL_SETUP.md
  - Gemfile
  - Gemfile.lock

# Custom variables
company:
  founded: 2025
  ein: "39-3468580"
  location: "Lafayette, Louisiana"